stages:
  process_data:
    cmd: python src/make_processed.py
    deps:
    - data/raw/creditcard.csv
    - src/make_processed.py
    outs:
    - data/processed/creditcard_clean.csv
  validate:
    cmd: python src/validate.py
    deps:
    - data/processed/creditcard_clean.csv
    - src/validate.py
    outs:
    - reports/validation.txt
